import { Inter } from "next/font/google";
import "@/src/app/globals.css";
import Head from "next/head";
import Script from "next/script";
import HeaderTop from "./component/HeaderTop";
import '@/public/assets/css/style.css';
import '@/public/assets/vendor/switcher/switcher.css';
import "@/public/assets/icons/font-awesome/css/all.min.css";
import "@/public/assets/icons/flaticon/flaticon_swigo.css";
import "@/public/assets/vendor/swiper/swiper-bundle.min.css";
import "@/public/assets/vendor/niceselect/css/nice-select.css";
import "@/public/assets/vendor/pickadate/lib/themes/default.css";
import "@/public/assets/vendor/pickadate/lib/themes/default.date.css";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "website",
  deScription: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <>
          {/* Favicon icon */}
          <link rel="icon" type="image/png" href="assets/images/favicon.png" />
          {/* Flaticon */}
           {/* <link rel="stylesheet" href="assets/icons/flaticon/flaticon_swigo.css" /> */}
          {/* Font Awesome */}
          <link rel="stylesheet" href="assets/icons/font-awesome/css/all.min.css" />
          {/* Swiper */}
          <link rel="stylesheet" href="assets/vendor/swiper/swiper-bundle.min.css" />
          {/* Nice Select */}
          <link rel="stylesheet" href="assets/vendor/niceselect/css/nice-select.css" />
          {/* PickDate */}
          <link
            rel="stylesheet"
            href="assets/vendor/pickadate/lib/themes/default.css"
          />
          <link
            rel="stylesheet"
            href="assets/vendor/pickadate/lib/themes/default.date.css"
          />
          {/* Google Fonts */}
          <link rel="preconnect" href="https://fonts.googleapis.com/" />
          <link rel="preconnect" href="https://fonts.gstatic.com/" crossOrigin="" />
          <link
            href="https://fonts.googleapis.com/css2?family=Lobster&family=Lobster+Two:ital,wght@0,400;0,700;1,400;1,700&family=Poppins:ital,wght@0,100;0,200;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
            rel="stylesheet"
          />
          {/* Custom Stylesheet */}
          <link rel="stylesheet" href="assets/css/style.css" />
          <link rel="stylesheet" href="assets/vendor/rangeslider/rangeslider.css" />
          <link rel="stylesheet" href="assets/vendor/switcher/switcher.css" />
        </>


      </Head>
      <body className={`box-border m-0 selection:bg-primary selection:text-white font-poppins ${inter.className}`} id="bg" >
        {/* <!-- Pointer ring --> */}
        <div id="cursor" className="sm:block hidden"></div>
        <div id="cursor-border" className="sm:block hidden"></div>

        {/* <!-- scrolltop-progress --> */}
        <div className="progress-wrap">
          <svg className="progress-circle svg-content" width="100%" height="100%" viewBox="-1 -1 102 102">
            <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98" />
          </svg>
        </div>
        <div className="page-wraper">
        <HeaderTop />
        </div>

        {children}


        <div className="menu-backdrop"></div>




        <Script src="/assets/js/jquery.min.js"></Script>
        {/* <!-- JQUERY.MIN JS --> */}
        <Script src="/assets/vendor/niceselect/js/jquery.nice-select.min.js"></Script>
        {/* <!-- NICE SELECT --> */}
        <Script src="/assets/vendor/swiper/swiper-bundle.min.js"></Script>
        {/* <!-- SWIPER --> */}
        {/* <!-- PICKDATE --> */}
        <Script src="/assets/vendor/pickadate/lib/picker.js"></Script>
        <Script src="/assets/vendor/pickadate/lib/picker.date.js"></Script>
        <Script src="/assets/vendor/pickadate/lib/picker.time.js"></Script>
        <Script src="/assets/js/dz.ajax.js"></Script>
        {/* <!-- AJAX --> */}
        <Script src="/assets/js/dz.carousel.js"></Script>
        {/* <!-- OWL CAROUSEL --> */}
        <Script src="/assets/js/custom.min.js"></Script>
        {/* <!-- CUSTOM.MIN.JS --> */}
        <Script src="/assets/vendor/rangeslider/rangeslider.js"></Script>
        {/* <!-- CUSTOM JS --> */}
        <Script src="/assets/js/dznav-init.js"></Script>
        {/* <!-- DZNAV INIT --> */}
        <Script src="/assets/vendor/switcher/switcher.js"></Script>
        {/* <!-- CUSTOM JS --> */}
      </body>
    </html>
  );
}
